Repository connect-foundation/2019-20, pull requests merged in 2019-11, with the labels that each got.

#15 깃헙 hooks를 이용하여 commit과 관련한 컨벤션 점검 자동화
  .gitignore
  commitlint.config.js
  lerna.json
  package.json
  scripts/check-branch-not-master.sh
  yarn.lock
Labels: environment, feature

#16 ESLint & Prettier 세팅
  .gitignore
  .prettierignore
  .prettierrc.js
  commitlint.config.js
  lerna.json
  package.json
  yarn.lock
Labels: environment, feature

#17 CI/CD를 위한 기초 github actions 설정
  .github/workflows/client-object-storage-nCloud.yml
  .github/workflows/react-build-test.yml
  .github/workflows/server-api-deploy.yml
  .github/workflows/server-api-test.yml
Labels: environment, feature

#18 공통으로 사용할 ExpressJS template 생성
  .eslintignore
  apis/template/README.md
  apis/template/app.js
  apis/template/bin/www
  apis/template/config/index.js
  apis/template/core/index.js
  apis/template/db/index.js
  apis/template/package.json
  apis/template/routes/index.js
  apis/template/scripts/index.js
  apis/template/services/index.js
  apis/template/tests/index.js
  apis/template/utils/index.js
  yarn.lock
Labels: environment, feature

#25 feat: add task template for Github issue
  .github/ISSUE_TEMPLATE/Task.md
Labels: environment, feature

#33 프로젝트에 환경(폴더 구조)에 따라 정상적으로 CI/CD가 가능하도록 수정
  .github/workflows/client-object-storage-nCloud.yml
  .github/workflows/react-build-test.yml
  .github/workflows/server-api-deploy.yml
  .github/workflows/server-api-test.yml
Labels: bug, environment

#37 Database 설계 및 제어
  .gitignore
  apis/product/.babelrc
  apis/product/.eslintignore
  apis/product/.eslintrc.json
  apis/product/README.md
  apis/product/app.js
  apis/product/bin/www.js
  apis/product/config/index.js
  apis/product/core/index.js
  apis/product/db/index.js
  apis/product/db/model/index.js
  apis/product/db/model/product.js
  apis/product/db/seeds/product.js
  apis/product/package.json
  apis/product/routes/index.js
  apis/product/scripts/index.js
  apis/product/services/index.js
  apis/product/tests/index.test.js
  apis/product/utils/index.js
  template.env
  yarn.lock
Labels: epic:상품관리, priority: 상, task

#44 프로젝트 소개 Readme 작성
  README.md
Labels: documentation

#38 HOTFIX : change babel setting
  apis/template/.babelrc
  apis/template/app.js
  apis/template/package.json
  yarn.lock
Labels: bug

#56 클라이언트 React 앱에 public 폴더를 추가하였습니다.
  .gitignore
  web-apps/client/public/favicon.ico
  web-apps/client/public/index.html
  web-apps/client/public/logo192.png
  web-apps/client/public/logo512.png
  web-apps/client/public/manifest.json
  web-apps/client/public/robots.txt
Labels: hot fix
