Repository connect-foundation/2019-20, pull requests merged in 2019-12, with the labels that each got.

#68 인증 서버 구현
  apis/auth/.babelrc
  apis/auth/.eslintignore
  apis/auth/.eslintrc.json
  apis/auth/README.md
  apis/auth/app.js
  apis/auth/assets/errorMessages.js
  apis/auth/assets/uris.js
  apis/auth/bin/www.js
  apis/auth/config/config.js
  apis/auth/config/index.js
  apis/auth/core/index.js
  apis/auth/core/userManagement.js
  apis/auth/db/index.js
  apis/auth/env.ssl
  apis/auth/migrations/20191205051150-create-user.js
  apis/auth/models/index.js
  apis/auth/models/user.js
  apis/auth/package.json
  apis/auth/public.pem
  apis/auth/routes/controller/errorHandler.js
  apis/auth/routes/controller/loginControl.js
  apis/auth/routes/controller/naverOAuth.js
  apis/auth/routes/index.js
  apis/auth/routes/middlewares/jwtValidator.js
  apis/auth/routes/middlewares/naverOAuth.js
  apis/auth/routes/middlewares/userManagement.js
  apis/auth/routes/naver.js
  apis/auth/scripts/dbInit.sh
  apis/auth/scripts/encriptENV.sh
  apis/auth/scripts/index.js
  apis/auth/seeders/20191205123247-demo-user.js
  apis/auth/services/index.js
  apis/auth/tests/index.test.js
  apis/auth/utils/corsOptions.js
  apis/auth/utils/detectError.js
  apis/auth/utils/index.js
  yarn.lock
Labels: epic:인증, priority: 중

#82 mongoosastic을 이용한 일래스틱 서치와 몽고DB연결에 따른 미들웨어 수정
  .github/workflows/server-api-deploy.yml
  apis/product/.babelrc
  apis/product/.eslintrc.json
  apis/product/app.js
  apis/product/core/code.js
  apis/product/core/index.js
  apis/product/core/message.js
  apis/product/core/string-conveter.js
  apis/product/db/model/product.js
  apis/product/db/seeds/20191209.json
  apis/product/db/seeds/product.js
  apis/product/env.ssl
  apis/product/package.json
  apis/product/routes/controller/deleteProduct.js
  apis/product/routes/controller/getProductInfo.js
  apis/product/routes/controller/info.js
  apis/product/routes/controller/modifyProduct.js
  apis/product/routes/controller/productListLookup.js
  apis/product/routes/controller/products.js
  apis/product/routes/controller/writeProduct.js
  apis/product/routes/info.js
  apis/product/routes/middleware/etag-generator.js
  apis/product/routes/middleware/listView.js
  apis/product/routes/product.js
  apis/product/run.sh
  apis/product/tests/mock-data.js
  apis/product/tests/mock-datas.js
  apis/product/tests/unit.test.js
Labels: environment, epic:상품검색

#60 상품 등록페이지 구현
  web-apps/client/package.json
  web-apps/client/src/assets/uris.js
  web-apps/client/src/components/addPicture.jsx
  web-apps/client/src/components/alertDialog.jsx
  web-apps/client/src/components/dealType.jsx
  web-apps/client/src/components/drawer.jsx
  web-apps/client/src/components/drawerList.jsx
  web-apps/client/src/components/header.jsx
  web-apps/client/src/components/imageList.jsx
  web-apps/client/src/components/loading.jsx
  web-apps/client/src/components/priceField.jsx
  web-apps/client/src/components/productForm.jsx
  web-apps/client/src/components/productImage.jsx
  web-apps/client/src/components/radioButton.jsx
  web-apps/client/src/contexts/productStore.jsx
  web-apps/client/src/hooks/useCredentialFetch.jsx
  web-apps/client/src/hooks/useFetch.jsx
  web-apps/client/src/hooks/useImageUpload.jsx
  web-apps/client/src/index.css
  web-apps/client/src/pages/newProduct.jsx
  web-apps/client/src/setupTests.js
  web-apps/client/src/utils/apiCall.js
  web-apps/client/src/utils/imageProcess.js
  web-apps/client/src/utils/resizeProcess.js
  web-apps/client/src/utils/util.js
  yarn.lock
Labels: epic:상품관리, priority: 상, task

#81 채팅방 구현
  web-apps/client/package.json
  web-apps/client/src/App.js
  web-apps/client/src/components/ChatBox.js
  web-apps/client/src/components/ChatInputField.js
  web-apps/client/src/components/ChatList.js
  web-apps/client/src/components/ChatRow.js
  web-apps/client/src/components/ChatSection.js
  web-apps/client/src/components/SectionHeader.js
  web-apps/client/src/contexts/socket.js
  web-apps/client/src/dummy/chat.js
  web-apps/client/src/hooks/useIntersect.js
  web-apps/client/src/index.css
  web-apps/client/src/index.js
  web-apps/client/src/pages/ChatRoom.js
  web-apps/client/src/pages/TmpChat.js
  web-apps/client/src/theme/muiTheme.js
  web-apps/client/src/types/index.js
  web-apps/client/src/utils/index.js
Labels: epic:채팅

#83 검색기능을 제외한 상품검색 필터(위치,카테고리,가격)
  .github/workflows/client-object-storage-nCloud.yml
  .github/workflows/react-build-test.yml
  web-apps/client/src/App.js
  web-apps/client/src/components/action-bar.js
  web-apps/client/src/components/card/content-section.js
  web-apps/client/src/components/card/image-section.js
  web-apps/client/src/components/card/index.js
  web-apps/client/src/components/card/style.js
  web-apps/client/src/components/card/time-function.js
  web-apps/client/src/components/checkbox-label.js
  web-apps/client/src/components/field.js
  web-apps/client/src/components/icon-buton.js
  web-apps/client/src/components/kakao-map/index.js
  web-apps/client/src/components/kakao-map/load-api-script.js
  web-apps/client/src/components/kakao-map/move-map-event.js
  web-apps/client/src/components/productForm.jsx
  web-apps/client/src/components/radius-input.js
  web-apps/client/src/components/snack-bar.js
  web-apps/client/src/components/tool-bar.js
  web-apps/client/src/components/two-number-input.js
  web-apps/client/src/contexts/filters.js
  web-apps/client/src/contexts/snackbar.js
  web-apps/client/src/contexts/socket.js
  web-apps/client/src/index.css
  web-apps/client/src/index.js
  web-apps/client/src/pages/area.js
  web-apps/client/src/pages/filters/category.js
  web-apps/client/src/pages/filters/index.js
  web-apps/client/src/pages/main/fetch.js
  web-apps/client/src/pages/main/index.js
  web-apps/client/src/pages/navigator.js
  web-apps/client/src/pages/newProduct.jsx
  web-apps/client/src/pages/notice.js
  web-apps/client/src/router.js
  web-apps/client/src/style.css
  web-apps/client/src/theme/index.js
  web-apps/client/src/utils/action-bar.js
  web-apps/client/src/utils/config.js
  web-apps/client/src/utils/time.js
  yarn.lock
Labels: epic:상품검색

#107 거리지정 슬라이더 처음부터 표시하게 변경 및 코드 리팩토링
  web-apps/client/src/components/address-list.js
  web-apps/client/src/components/kakao-map.js
  web-apps/client/src/components/kakao-map/index.js
  web-apps/client/src/components/kakao-map/load-api-script.js
  web-apps/client/src/components/kakao-map/move-map-event.js
  web-apps/client/src/contexts/filters.js
  web-apps/client/src/hooks/use-load-script.js
  web-apps/client/src/pages/area.js
  web-apps/client/src/utils/index.js
Labels: epic:상품검색

#98 FE: 인증 과정 추가
  web-apps/client/package.json
  web-apps/client/public/index.html
  web-apps/client/public/logo.png
  web-apps/client/src/App.js
  web-apps/client/src/assets/naverLogIn.png
  web-apps/client/src/assets/oemarket.png
  web-apps/client/src/assets/uris.js
  web-apps/client/src/components/addPicture.jsx
  web-apps/client/src/components/alertDialog.jsx
  web-apps/client/src/components/logo.jsx
  web-apps/client/src/components/naverLogInButton.jsx
  web-apps/client/src/components/priceField.jsx
  web-apps/client/src/components/productForm.jsx
  web-apps/client/src/components/skipLogInButton.jsx
  web-apps/client/src/contexts/alertMessage.jsx
  web-apps/client/src/contexts/productStore.jsx
  web-apps/client/src/contexts/user.js
  web-apps/client/src/contexts/user.jsx
  web-apps/client/src/index.css
  web-apps/client/src/pages/entrance.jsx
  web-apps/client/src/pages/main/index.js
  web-apps/client/src/pages/navigator.js
  web-apps/client/src/pages/newProduct.jsx
  web-apps/client/src/pages/setMyArea.jsx
  web-apps/client/src/utils/apiCall.js
  yarn.lock
Labels: epic:인증, priority: 중

#106 상품 상세 페이지 관련 구현 및 연동
  web-apps/client/package.json
  web-apps/client/src/App.js
  web-apps/client/src/assets/cssText.js
  web-apps/client/src/assets/list.js
  web-apps/client/src/assets/messages.js
  web-apps/client/src/assets/uris.js
  web-apps/client/src/components/Carousel.jsx
  web-apps/client/src/components/LogOutButton.jsx
  web-apps/client/src/components/ProductFooter.jsx
  web-apps/client/src/components/addPicture.jsx
  web-apps/client/src/components/alertDialog.jsx
  web-apps/client/src/components/chatLink.jsx
  web-apps/client/src/components/goBackButton.jsx
  web-apps/client/src/components/header.jsx
  web-apps/client/src/components/headerInProduct.jsx
  web-apps/client/src/components/imageList.jsx
  web-apps/client/src/components/interest.jsx
  web-apps/client/src/components/priceInformation.jsx
  web-apps/client/src/components/productDescription.jsx
  web-apps/client/src/components/productForm.jsx
  web-apps/client/src/components/productImage.jsx
  web-apps/client/src/components/productProfile.jsx
  web-apps/client/src/components/sellerInfo.jsx
  web-apps/client/src/components/tool-bar.js
  web-apps/client/src/contexts/ImageStore.jsx
  web-apps/client/src/contexts/alertMessage.jsx
  web-apps/client/src/contexts/user.jsx
  web-apps/client/src/hooks/useFetch.jsx
  web-apps/client/src/hooks/useWindowSize.jsx
  web-apps/client/src/index.css
  web-apps/client/src/pages/ProductDetail.jsx
  web-apps/client/src/pages/entrance.jsx
  web-apps/client/src/pages/newProduct.jsx
  web-apps/client/src/utils/apiCall.js
  web-apps/client/src/utils/index.js
  web-apps/client/src/utils/object.js
  yarn.lock
Labels: epic:상품관리, priority: 상, task

#100 Auth api- 네아로 구현
  apis/auth/app.js
  apis/auth/assets/errorMessages.js
  apis/auth/assets/uris.js
  apis/auth/core/userManagement.js
  apis/auth/migrations/20191205051150-create-user.js
  apis/auth/models/user.js
  apis/auth/package.json
  apis/auth/routes/controller/errorHandler.js
  apis/auth/routes/controller/loginControl.js
  apis/auth/routes/controller/publicInformation.js
  apis/auth/routes/index.js
  apis/auth/routes/middlewares/userManagement.js
  apis/auth/seeders/20191205123247-demo-user.js
  apis/auth/tests/index.test.js
  apis/auth/utils/corsOptions.js
  apis/auth/utils/index.js
Labels: epic:인증, priority: 중, task

#101 Product api - 사진 업로드
  apis/product/app.js
  apis/product/assets/uri.js
  apis/product/config/awsConfig.js
  apis/product/config/multipart.js
  apis/product/core/callAPI.js
  apis/product/core/index.js
  apis/product/db/model/product.js
  apis/product/db/seeds/20191209.json
  apis/product/package.json
  apis/product/routes/controller/imageControl.js
  apis/product/routes/controller/products.js
  apis/product/routes/picture.js
  apis/product/routes/product.js
  apis/product/tests/unit.test.js
  yarn.lock
Labels: epic:상품관리, priority: 상, task

#105 상품검색 페이지
  web-apps/client/package.json
  web-apps/client/src/App.js
  web-apps/client/src/assets/uris.js
  web-apps/client/src/components/Search.jsx
  web-apps/client/src/contexts/Filters.jsx
  web-apps/client/src/contexts/User.jsx
  web-apps/client/src/hooks/useFetch.jsx
  web-apps/client/src/pages/ProductDetail.jsx
  web-apps/client/src/pages/Search.jsx
  web-apps/client/src/pages/main/fetch.js
  web-apps/client/src/pages/main/index.js
Labels: epic:상품검색, feature, task
